/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      screens: {
        'nav-desktop': '1070px',
      },
      colors: {
        "on-tertiary-container": "#797982",
        "surface-dim": "#121415",
        "inverse-primary": "#5f5e5f",
        "primary-fixed": "#e5e2e3",
        "secondary-container": "#474649",
        "surface-container-highest": "#333536",
        "background": "#121415",
        "surface-container-lowest": "#0c0e0f",
        "surface": "#121415",
        "inverse-surface": "#e2e2e3",
        "on-primary-fixed": "#1c1b1c",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#474649",
        "secondary-fixed-dim": "#c8c6c8",
        "on-primary": "#313031",
        "surface-variant": "#333536",
        "outline": "#919094",
        "on-surface-variant": "#c7c6ca",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#474647",
        "on-surface": "#e2e2e3",
        "primary-container": "#0a0a0b",
        "tertiary": "#c7c5d0",
        "on-error": "#690005",
        "secondary-fixed": "#e4e2e4",
        "inverse-on-surface": "#2f3132",
        "on-tertiary-fixed": "#1a1b23",
        "on-tertiary": "#2f3038",
        "surface-container-high": "#282a2b",
        "on-background": "#e2e2e3",
        "on-secondary-container": "#b6b4b7",
        "primary": "#c8c6c7",
        "tertiary-fixed-dim": "#c7c5d0",
        "surface-bright": "#38393a",
        "tertiary-fixed": "#e3e1ec",
        "on-tertiary-fixed-variant": "#46464f",
        "on-secondary": "#303032",
        "surface-tint": "#c8c6c7",
        "surface-container": "#1e2021",
        "secondary": "#c8c6c8",
        "outline-variant": "#46464a",
        "tertiary-container": "#090a11",
        "primary-fixed-dim": "#c8c6c7",
        "surface-container-low": "#1a1c1d",
        "on-secondary-fixed": "#1b1b1d",
        "on-primary-container": "#7a797a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "24px",
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "32px",
        "margin-desktop": "64px",
        "section-gap": "160px"
      },
      fontFamily: {
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "display-hero": ["Libre Caslon Text"],
        "mono-code": ["Geist"],
        "label-caps": ["Geist"],
        "headline-lg": ["Libre Caslon Text"],
        "display-hero-mobile": ["Libre Caslon Text"],
        "body-lg": ["Geist"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["clamp(2.25rem, 8vw, 5.25rem)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "mono-code": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["clamp(1.75rem, 5vw, 3rem)", { lineHeight: "1.2", fontWeight: "400" }],
        "display-hero-mobile": ["clamp(1.75rem, 6vw, 3rem)", { lineHeight: "1.15", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
